// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"liuhuo23/liuos/internal/app"
	"liuhuo23/liuos/internal/data"
	"liuhuo23/liuos/internal/server"
)

// Injectors from wire.go:

func InitializeApp() *app.App {
	appConfig := app.NewAppConfig()
	echo := server.NewEcho()
	databaseConfig := app.NewDatabaseConfig(appConfig)
	db := data.NewDb(databaseConfig)
	appApp := app.NewApp(appConfig, echo, db)
	return appApp
}
