// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"liuhuo23/liuos/internal/conf"
	"liuhuo23/liuos/internal/server"
	"liuhuo23/liuos/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	healthSrv := service.NewHealthSrv()
	openapiService := service.NewOpenapiService(confServer)
	httpServer := server.NewHTTPServer(confServer, logger, healthSrv, openapiService)
	app := newApp(logger, httpServer)
	return app, func() {
	}, nil
}
