// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: health/v1/health.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HealthSvc_CheckHealth_FullMethodName = "/health.v1.healthSvc/CheckHealth"
)

// HealthSvcClient is the client API for HealthSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthSvcClient interface {
	CheckHealth(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HelloReply, error)
}

type healthSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthSvcClient(cc grpc.ClientConnInterface) HealthSvcClient {
	return &healthSvcClient{cc}
}

func (c *healthSvcClient) CheckHealth(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HelloReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, HealthSvc_CheckHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthSvcServer is the server API for HealthSvc service.
// All implementations must embed UnimplementedHealthSvcServer
// for forward compatibility.
type HealthSvcServer interface {
	CheckHealth(context.Context, *emptypb.Empty) (*HelloReply, error)
	mustEmbedUnimplementedHealthSvcServer()
}

// UnimplementedHealthSvcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthSvcServer struct{}

func (UnimplementedHealthSvcServer) CheckHealth(context.Context, *emptypb.Empty) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckHealth not implemented")
}
func (UnimplementedHealthSvcServer) mustEmbedUnimplementedHealthSvcServer() {}
func (UnimplementedHealthSvcServer) testEmbeddedByValue()                   {}

// UnsafeHealthSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthSvcServer will
// result in compilation errors.
type UnsafeHealthSvcServer interface {
	mustEmbedUnimplementedHealthSvcServer()
}

func RegisterHealthSvcServer(s grpc.ServiceRegistrar, srv HealthSvcServer) {
	// If the following call pancis, it indicates UnimplementedHealthSvcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealthSvc_ServiceDesc, srv)
}

func _HealthSvc_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthSvcServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthSvc_CheckHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthSvcServer).CheckHealth(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthSvc_ServiceDesc is the grpc.ServiceDesc for HealthSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "health.v1.healthSvc",
	HandlerType: (*HealthSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckHealth",
			Handler:    _HealthSvc_CheckHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "health/v1/health.proto",
}
